version: "3"

services:
    api:
        image: node:lts
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - ./api:/app
        working_dir: "/app"
        command: ["npm", "start"]

    db:
        image: mongo:4
        restart: always
        ports:
            # port de la machine : port du conteneur
            - "27018:27017"

        command: ["mongod", "--auth"]
        environment:
            # MONGO_INITDB_DATABASE: $db
            # MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
            # MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
            MONGO_INITDB_DATABASE: dbcomicscollect
            MONGO_INITDB_ROOT_USERNAME: comicsco
            MONGO_INITDB_ROOT_PASSWORD: mdp
        volumes:
            - db-comics-collect:/data/db

volumes:
    db-comics-collect:
