version: "3"

services:
  api:
    image: node:lts
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    working_dir: "/app"
    command: ["npm", "start"]

  db:
    image: mongo:4
    restart: always
    ports:
      # port de la machine : port du conteneur
      - "27018:27017"

    command: ["mongod", "--auth"]
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - example_db:/data/db

volumes:
  example_db:
